# Generated by Django 2.2.7 on 2019-12-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='CPA',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
